---
- name: install mysql mariadb-serve install
  hosts: dbserver
  become: true
  tasks:
    - name: install mariadb-server
      yum:
        name: mariadb105-server
        state: latest
      
    - name: sql file copy 
      copy:
        src: ./source/create_db_webtest.sql
        dest: /tmp/create_db_webtest.sql
        mode: 0664
    - name: execute mariadb
      systemd:
        name: mariadb
        state: started
      # notify : execute_sql

    - name: Execute SQL file using MySQL Client
      shell: "mysql -uroot < /tmp/create_db_webtest.sql"
      register: db_result
      ignore_errors: true
    - debug:
        var: db_result
          
   # - handlers:
    #- name: execute_sql 
        
          
